### ISSUE TITLE
正常配置action也不能运行

### ISSUE THREAD

**Issue by Kirrito-k423** [Jzhhh-Syuuu/BiliBiliDailyTask#2]
```
Run dotnet run -p ./src/Ray.BiliBiliTool.Console -userId=${userId} -sessData=${sessData} -biliJct=${biliJct} -closeConsoleWhenEnd=1 ${otherConfigs}
[08:44:14 INF] -----任务启动-----
[08:44:14 INF] -----开始【登录】-----
[08:44:15 FTL] 登录失败，任务结束。Msg:One or more errors occurred. (Response status code does not indicate success: 4[12](https://github.com/Kirrito-k423/BiliBiliDailyTask/runs/7059608465?check_suite_focus=true#step:6:13) (Precondition Failed).)
[08:44:15 ERR] 程序发生异常：登录失败，请检查Cookie
Unhandled exception. System.Exception: 登录失败，请检查Cookie
   at Ray.BiliBiliTool.Application.DailyTaskAppService.Login() in /home/runner/work/BiliBiliDailyTask/BiliBiliDailyTask/src/Ray.BiliBiliTool.Application/DailyTaskAppService.cs:line 71
   at Ray.BiliBiliTool.Application.DailyTaskAppService.DoDailyTask() in /home/runner/work/BiliBiliDailyTask/BiliBiliDailyTask/src/Ray.BiliBiliTool.Application/DailyTaskAppService.cs:line 42
   at Ray.BiliBiliTool.Console.Program.StartRun() in /home/runner/work/BiliBiliDailyTask/BiliBiliDailyTask/src/Ray.BiliBiliTool.Console/Program.cs:line 83
   at Ray.BiliBiliTool.Console.Program.Main(String[] args) in /home/runner/work/BiliBiliDailyTask/BiliBiliDailyTask/src/Ray.BiliBiliTool.Console/Program.cs:line 25
Error: Process completed with exit code [13](https://github.com/Kirrito-k423/BiliBiliDailyTask/runs/7059608465?check_suite_focus=true#step:6:14)4.
```
![image](https://user-images.githubusercontent.com/44373239/175806756-01b22468-8d87-4677-8554-e06c16637a06.png)

**Comment by Kirrito-k423** [comment]
隔壁的项目可以运行，但是要check一下投币的代码，一开始扣了我50币，血亏
